name: Olivier CORRE
favicon: null
layout_spectrum: 0.5467346126679331
typography_spectrum: 0.3084103502333164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#313f49'
    - '#6f817e'
    - '#201f24'
    - '#e0dfd6'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.7698008131701499
purpose: []
